### ISSUE TITLE
Latest version produces syntax error on compilation

### ISSUE THREAD

**Issue by davletovalmir** [slime-lang/phoenix_slime#47]
Hi, I've updated my `mix.exs` to fetch `phoenix_slime` right from repo:
```elixir
{:phoenix_slime, github: "slime-lang/phoenix_slime", override: true}
```
But it produces syntax error on compilation.

Any ideas why? Maybe related to recent update of slime version?

```
== Compilation error on file lib/myproject/web/views/layout_view.ex ==
** (Slime.TemplateSyntaxError) {:no_match, "\n"}
INPUT, Line 1, Column 1

^

    lib/slime/parser.ex:27: Slime.Parser.handle_syntax_error/3
    lib/slime/renderer.ex:17: Slime.Renderer.precompile/1
    lib/phoenix_slime/engine.ex:9: PhoenixSlime.Engine.compile/2
    (phoenix) lib/phoenix/template.ex:378: Phoenix.Template.compile/2
    (phoenix) lib/phoenix/template.ex:186: Phoenix.Template."-MACRO-__before_compile__/2-fun-0-"/3
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix) expanding macro: Phoenix.Template.__before_compile__/1
    lib/myproject/web/views/layout_view.ex:1: MyProject.Web.LayoutView (module)
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```
My elixir version:
```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.4.5
```

**Comment by fbjork** [comment]
@doomspork any thoughts how to fix that?

**Comment by doomspork** [comment]
Not off the top of my head @fbjork!  Do either yourself or @davletovalmir have an example project I could look at?

**Comment by doomspork** [comment]
@davletovalmir have you figured this out?  If not, could you share the slime that generated the error?

**Comment by jlgeering** [comment]
for me it was when the slime started with an empty line:
```

div me no like empty line
```

**Comment by doomspork** [comment]
Thank you for the report @jlgeering!
