### ISSUE TITLE
Error when try to set `selected` attribute on slimleex

### ISSUE THREAD

**Issue by rjurado01** [slime-lang/phoenix_slime#81]
I have this line:

`option(value="#{page_size}") =page_size`

and I'm trying to add `selected` attribute to selected option like [here](https://github.com/joerichsen/phoenix_live_view_example/blob/table_example/lib/demo_web/live/table_live.ex#L47): 

``option(value="#{page_size}" ="#{page_size == @page.size && 'selected' || ''}") =page_size``

but I get this error when I try:

```
Compiling 1 file (.ex)

== Compilation error in file lib/app_web/views/user_view.ex ==
** (Slime.TemplateSyntaxError) Unexpected indent
INPUT, Line 31, Column 0
  select(name="page_size")
^

    (slime) lib/slime/parser.ex:14: Slime.Parser.parse/1
    (slime) lib/slime/renderer.ex:17: Slime.Renderer.precompile/1
    (phoenix_slime) lib/phoenix_slime/live_view_engine.ex:9: PhoenixSlime.LiveViewEngine.compile/2
    (phoenix) lib/phoenix/template.ex:355: Phoenix.Template.compile/3
    (phoenix) lib/phoenix/template.ex:166: anonymous fn/4 in Phoenix.Template."MACRO-__before_compile__"/2
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (phoenix) expanding macro: Phoenix.Template.__before_compile__/1
    lib/app_web/views/user_view.ex:1: AppWeb.UserView (module)
    (elixir) lib/kernel/parallel_compiler.ex:229: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
Compiling 1 file (.ex)
```

How can I do this?

**Comment by Rakoth** [comment]
Did you try to follow the example from https://github.com/slime-lang/slime#attributes ?

```
option value=page_size selected=(page_size == @page.size) =page_size
```

**Comment by rjurado01** [comment]
That works !! Thank, I overlooked that example.
